#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#feh --bg-fill /home/pobe/Imágenes/wallpaperbetter.jpg
feh --bg-fill /home/pobe/Imágenes/thumb-1920-1054068.png
#feh --bg-fill /home/pobe/Imágenes/3650667.jpg
#feh --bg-fill /home/pobe/Imágenes/thumb-1920-632051.png
~/.config/polybar/./launch.sh
bspc config focus_follows_pointer true
picom --experimental-backends &
bspc config border_width 0
export target = "Not target"
